# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.5.1
clone:
  depth: full
pipelines:
  branches:
    production:
      - step:
          # set HEROKU_API_KEY and HEROKU_APP_NAME environment variables
          # set clone `depth: full' as described here: https://confluence.atlassian.com/x/Y9-5Mw
          name: Deploying from Bitbucket Pipeline -> Heroku
          deployment: production  # set to test, staging or production
          # trigger: manual  # uncomment to have a manual step
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
    #staging:
    #- step:
        # set HEROKU_API_KEY and HEROKU_APP_NAME environment variables
        # set clone `depth: full' as described here: https://confluence.atlassian.com/x/Y9-5Mw
    #    name: Deploying from Bitbucket Pipeline -> Heroku
    #    deployment: staging  # set to test, staging or production
        # trigger: manual  # uncomment to have a manual step
    #    script:
    #    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP_NAME.git HEAD:master