- 
  inquiry: 99980
  company: Contract Labour
- 
  inquiry: 99981
  company: FDI Investment
- 
  inquiry: 99982
  company: Bill Discount
- 
  inquiry: 99983
  company: Credit Card
- 
  inquiry: 99984
  company: BG
- 
  inquiry: 99985
  company: Bank Interest
- 
  inquiry: 99986
  company: Tender
- 
  inquiry: 99987
  company: Transfer
- 
  inquiry: 99988
  company: Rent Exp
- 
  inquiry: 99989
  company: Receipt
- 
  inquiry: 99990
  company: inter bank contra
- 
  inquiry: 99991
  company: Statutory Payment
- 
  inquiry: 99992
  company: Expenses
- 
  inquiry: 99993
  company: Salary
- 
  inquiry: 99994
  company: Petty Cash
- 
  inquiry: 99995
  company: Advance to Staff on Account
- 
  inquiry: 99996
  company: on a/c incoming payment
- 
  inquiry: 99997
  company: 99997-Advance Payment
- 
  inquiry: 99998
  company: 99998 - Open PO
- 
  inquiry: 99999
  company: 99999-Office Purchase
- 
  inquiry: 999991	
  company: inter bank contra
- 
  inquiry: 999992	
  company: Loan
- 
  inquiry: 9999991
  company: TERM DEPOSIT