development:
  adapter: postgresql

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: bulkmro_staging

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: bulkmro_production
