# config/chewy.yml
# separate environment configs
test:
  host: 'localhost:9250'
  prefix: 'test'
development:
  host: 'https://827f5059a1434cff07f01679651d5284.eu-west-1.aws.found.io'
  user: 'elastic'
  password: 'bDLp8QA9dujzvMm2WlHKstos'
  scheme: 'https'
production:
  host: <%= ENV["FOUNDELASTICSEARCH_URL"] %>
  user: <%= ENV["ELASTIC_USER_NAME"] %>
  password: <%= ENV["ELASTIC_PASSWORD"] %>
  scheme: 'https'
staging:
  host: <%= ENV["FOUNDELASTICSEARCH_URL"] %>
  user: <%= ENV["ELASTIC_USER_NAME"] %>
  password: <%= ENV["ELASTIC_PASSWORD"] %>
  scheme: 'https'