# config/chewy.yml
# separate environment configs
test:
  host: 'localhost:9250'
  prefix: 'test'
development:
  host: 'localhost:9200'
production:
  host: <%= ENV["FOUNDELASTICSEARCH_URL"] %>
  user: <%= ENV["ELASTIC_USER_NAME"] %>
  password: <%= ENV["ELASTIC_PASSWORD"] %>
  scheme: 'https'
staging:
  host: es-prod-bulkmro-com.centralindia.cloudapp.azure.com:9200
  user: ''
  password: ''
  scheme: 'http'