- 
  title: Abbreviations
  slug: abbreviations
  type: text
  url: "cool"
- 
  title: AR Invoice requests
  slug: ar_invoice_requests
  type: video
  url: "https://bulkmro-public-files.s3.amazonaws.com/Logistics/create_ar_invoice_request.mp4"
- 
  title: Create GRPO request
  slug: create_grpo_request
  type: video
  url: "https://bulkmro-public-files.s3.amazonaws.com/Logistics/create_grpo_request.mp4"
- 
  title: Create Inward dispatch
  slug: create_inward_dispatch
  type: video
  url: "https://bulkmro-public-files.s3.amazonaws.com/Logistics/create_inward_dispatch.mp4"
- 
  title: Create New quotation
  slug: create_new_quotation
  type: video
  url: "https://drive.google.com/file/d/1kOajXT-URWgKKcI4Ty3Q_j-ilJSxMeIQ/view?usp=share_link"
- 
  title: Create New sales order
  slug: create_new_sales_order
  type: video
  url: "https://drive.google.com/file/d/1FsY_0j7Qk9GV08iVsptvMEWFzPnk0dKd/view?usp=share_link"
- 
  title: Create Outward dispatch
  slug: create_outward_dispatch
  type: video
  url: "https://bulkmro-public-files.s3.amazonaws.com/Logistics/create_outward_dispatch.mp4"
- 
  title: Create Supplier PO
  slug: create_supplier_po
  type: video
  url: "https://drive.google.com/file/d/1ehQse36BKvMMzsWh22PiqcNlbvbLUdyI/view?usp=share_link"
- 
  title: Create New Inquiry
  slug: create_new_inquiry
  type: video
  url: "https://drive.google.com/file/d/1G5CiFUdLjmd0VMRwcwjvIt22tK7BfePd/view?usp=share_link"
- 
  title: Link Supplier
  slug: link_supplier
  type: video
  url: "https://drive.google.com/file/d/1ka7mzNaaeywlQy2GJ6dhFvcmPk4T_lPw/view?usp=share_link"
- 
  title: Customer Portal
  slug: customer_portal
  type: text
  url: "https://docs.google.com/document/d/1XG8kdCXgwl2ZiHH3wcdOLTNBaB5XIm3qIeHc-DaP6kA/edit?usp=share_link"
- 
  title: Bulk upload feature
  slug: bulk_upload_feature
  type: video
  url: "https://drive.google.com/file/d/1aN2WeQFsW5YFtpTBds59wO9NrkO1OPtR/view?usp=share_link"
- 
  title: Update material rediness follow_up
  slug: update_material_rediness_follow_up
  type: video
  url: "https://bulkmro-public-files.s3.amazonaws.com/Logistics/update_material_rediness_follow_up.mp4"
- 
  title: Add products to Sprint
  slug: add_products_to_sprint
  type: text
  url: "https://docs.google.com/document/d/1KhLRDI1WK1GTeuwPKy9n4IbtPG3ZwkRuXrmP9a3vhaA/edit?usp=share_link"