class Services::Overseers::PurchaseOrders::CreatePurchaseOrder < Services::Shared::BaseService
  def initialize(po_request, params)
    @po_request = po_request
    @params = params
  end

  def call
    purchase_order = PurchaseOrder.new
    purchase_order.assign_attributes(set_attributes)
    purchase_order.save!
    po_request.update_attributes(purchase_order_id: purchase_order.id)
  end

  def set_attributes
    {
        inquiry_id: po_request.inquiry.id,
        po_number: nil,
        metadata: set_metadata,
        created_by_id: params[:overseer].id,
        updated_by_id: params[:overseer].id,
        status: PurchaseOrder.statuses.key(35),
        payment_option_id: po_request.payment_option.present? ? po_request.payment_option.id : nil,
        logistics_owner_id: params[:overseer].id,
        company_id: po_request.supplier_id,
        is_partial: false
    }
  end

  def set_metadata
    {
        "PoCst": "0",
        "PoNum": "402000311",
        "PoRcm": "Regular",
        "PoDate": "2019-04-27",
        "PoPaid": "0",
        "PoSent": "0",
        "PoType": "Movement of Goods",
        "Series": "",
        "action": "create",
        "DocType": "",
        "ObjType": "",
        "ReqDate": "",
        "SlpCode": "",
        "po_type": "",
        "DocEntry": "13564",
        "ItemLine": [],
        "JrnlMemo": "",
        "PoStatus": "63",
        "PoSupNum": "SC-209236",
        "PoCarrier": "",
        "PoCustCom": "",
        "PoCustGst": "",
        "PoCustZip": "",
        "PoFreight": "Extra",
        "PoOrderId": "402000311",
        "PoRemarks": "",
        "PoShipper": "",
        "PoTaxRate": "CSG@18",
        "U_LogoMgr": "0",
        "po_LR_num": "",
        "PoComments": "",
        "PoCurrency": "INR",
        "PoCustCity": "",
        "PoCustName": "28788",
        "PoFinished": "0",
        "PoIsLocked": "0",
        "PoZollCost": "0.00",
        "ShipToCode": "",
        "controller": "callbacks/purchase_orders",
        "po_LR_date": "",
        "PoCustCount": "",
        "PoCustStadd": "",
        "PoCustState": "",
        "PoEnquiryId": "33462",
        "PoUpdatedAt": "2019-04-27",
        "PoInvoiceRef": " ",
        "PoSupplyDate": "2019-04-27",
        "PoTrackingid": "",
        "U_LogoPerson": "0",
        "po_insurance": "",
        "PoDestination": "Bulk MRO",
        "PoInvoiceDate": "2019-04-27",
        "PoMediaboxNum": "",
        "PoPaymentDate": "2019-04-27",
        "PoPaymentType": "",
        "PoSupBillFrom": "A218432",
        "PoSupShipFrom": "A218432",
        "PaymentDueDate": "",
        "PoAccessDuties": "",
        "PoDataVerified": "0",
        "PoFollowUpDate": "",
        "PoMissingPrice": "0",
        "PoPaymentTerms": "20% Advance and 80% before dispatch",
        "PoShippingCost": "0",
        "PoZollCostBase": "0.00",
        "po_import_port": "",
        "po_vehicle_num": "",
        "po_vessel_name": "",
        "purchase_order": {},
        "PoAdditionalPdf": "",
        "PoCommittedDate": "2019-04-27",
        "PoDeliveryTerms": "EXW",
        "PoShipWarehouse": "2",
        "po_shipping_tax": "",
        "PoAdditionalPdf1": "",
        "PoAdditionalPdf2": "",
        "PoBillingAddress": "A218432",
        "PoEndDestination": "",
        "PoLastNotifyText": "",
        "PoModeOfTrasport": "Road",
        "po_eway_bill_num": "",
        "po_sales_manager": "",
        "po_shipping_cost": "",
        "po_shipping_name": "",
        "PoDeliveryPercent": "0",
        "PoTargetWarehouse": "2",
        "po_overall_margin": "0",
        "po_shipping_tax_2": "",
        "po_shipping_tax_3": "",
        "PoShippingCostBase": "0.00",
        "PoSupplierOrderRef": "",
        "po_additional_pdf1": "",
        "po_port_of_loading": "",
        "po_shipping_cost_2": "",
        "po_shipping_cost_3": "",
        "po_shipping_name_2": "",
        "po_shipping_name_3": "",
        "PoPackingForwarding": "",
        "PoCurrencyChangeRate": "1",
        "po_port_of_discharge": "",
        "PoSupplierInvoiceDate": "",
        "PoExternalExtendedCost": "0",
        "PoSupplierInvoiceNumber": "",
        "PoDefaultProductDiscount": "0.00",
        "PoSupplierNotificationDate": "",
        "po_terms_of_delivery_payment": ""
    }
  end

  def item_line_json
    {
        "PopHsn": "7308",
        "PopNum": "",
        "PopQty": "650",
        "Linenum": "0",
        "OcrCode": "",
        "SlpCode": "79",
        "UnitMsr": "Manual",
        "WhsCode": "2",
        "OcrCode2": "",
        "OcrCode3": "",
        "OcrCode4": "",
        "OcrCode5": "",
        "PopEcoTax": "0.0000",
        "PopWeight": "0",
        "PopPriceHt": "1580",
        "PopTaxRate": "CSG@18",
        "PriceBefDi": "1580",
        "PopDiscount": "0",
        "PopOrderNum": "402000311",
        "PopProductId": "2ruLYk",
        "PopEcoTaxBase": "0.0000",
        "PopPackagingId": "",
        "PopPriceHtBase": "1580",
        "PopProductName": "BULK MRO APPROVED Galvanized Anti Skid Scaffolding Plank, Length 3 Mtr, Width 300 mm",
        "PopSuppliedQty": "650",
        "PopSupplierRef": "",
        "PopDeliveryDate": "2019-04-27",
        "PopExtendedCosts": "0.000",
        "PopPackagingName": "",
        "PopPackagingValue": "",
        "PopExtendedCostsBase": "0.000"
    }
  end

  attr_accessor :po_request, :params
end
