email_messages:
  from: nobody@bulkmro.com

slack:
  access_token: xoxp-395906857286-395824799415-397063976980-c73aaf550513f95e7fdff829317b1640
  bot_user_access_token: xoxb-395906857286-397063978996-v0clkA03XHgC2AZcsHm8F7cF

sendgrid:
  username: bulk
  password: GhgjIH4zw3p2
  api_key: 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

domain: www.bulkmro.com

twilio:
  phone: +919987480784
  messaging_service_sid: MGdddcada47fcc5123ebda5c7312dc086d
  account_sid: AC058d3c9497692b0adef3e7fa5655ed32
  auth_token: 72905dfd297bc2ea39afc029f57ba3da

azure:
  storage_account_name: bulkmro
  storage_access_key: HYecY13hBtJUsqup03iqK2gG1B6FOVbnNkIigo7ZgpfKMCLcjRZe6b19SIhaXH/nvnE/HVkNcSkfTsZilZTfDA==
  container: sprint

msg91:
  sender_id: BLKMRO
  auth_key: 220892AIFjiJYI5b6d37f3