email_messages:
  from: no-reply@bulkmro.com
  from_name: Bulk MRO Notifications
  reply_to: care@bulkmro.com
  reply_to_name: Bulk MRO Support

slack:
  bot_user_access_token: xoxb-395906857286-397063978996-v0clkA03XHgC2AZcsHm8F7cF
  username: Sprint Bot
  icon_emoji: ':moneybag:'

sendgrid:
  username: bulk
  password: GhgjIH4zw3p2
  api_key: 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

domain: www.bulkmro.com

twilio:
  phone: +919987480784
  messaging_service_sid: MGdddcada47fcc5123ebda5c7312dc086d
  account_sid: AC058d3c9497692b0adef3e7fa5655ed32
  auth_token: 72905dfd297bc2ea39afc029f57ba3da

azure:
  storage_account_name: bulksprint
  storage_access_key: bQHdNppONx0Tv5ye7jGxY+N437XWOjoBbrlQ6YY0nGT9TU3eb2Pjr7rzSFyxbAccCCKv8tEZJgBIY2ersM9Zbw==
  container: sprint

msg91:
  sender_id: BLKMRO
  auth_key: 220892AIFjiJYI5b6d37f3