omniauth:
  google_oauth2:
    client_id: 436964214631-llt53r38ks78k5afam2r751f9nhkg1ae.apps.googleusercontent.com
    client_secret: rtOMQ1p8G8kjTThgxN7olU5_

email_messages:
  from: no-reply@bulkmro.com
  from_name: Bulk MRO Notifications
  reply_to: care@bulkmro.com
  reply_to_name: Bulk MRO Support

primary_bank:
  name: Kotak Mahindra Bank Ltd
  address: Aum Saheel Tower, Mumbai 400080.
  account_name: Bulk MRO Industrial Supply Pvt. Ltd.
  account_number: 9412329433
  neft_code: KKBK0001411
  swift_code: KKBKINBB
  currency_usd:
    account_number: 9412666668
  currency_gbp:
    account_number: 9412666675
  currency_eur:
    account_number: 9412666682

secondary_bank:
  name: State Bank of India
  address: Kalpa Taru - 39, Pedder Road, Mumbai 400026.
  account_name: Bulk MRO Industrial Supply Pvt. Ltd.
  account_number: 35924122136
  neft_code: SBIN0000510

slack:
  bot_user_access_token: xoxb-395906857286-397063978996-v0clkA03XHgC2AZcsHm8F7cF
  username: Sprint Bot
  icon_emoji: ':moneybag:'

sendgrid:
  username: bulk
  password: GhgjIH4zw3p2
  api_key: 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

domain: sprint.bulkmro.com

twilio:
  phone: +919987480784
  messaging_service_sid: MGdddcada47fcc5123ebda5c7312dc086d
  account_sid: AC058d3c9497692b0adef3e7fa5655ed32
  auth_token: 72905dfd297bc2ea39afc029f57ba3da

azure:
  storage_account_name: bulksprint
  storage_access_key: bQHdNppONx0Tv5ye7jGxY+N437XWOjoBbrlQ6YY0nGT9TU3eb2Pjr7rzSFyxbAccCCKv8tEZJgBIY2ersM9Zbw==
  container: sprint

msg91:
  sender_id: BLKMRO
  auth_key: 220892AIFjiJYI5b6d37f3

wit:
  auth_token: E4C6GLQOFR4FPNUGUIUDCK3W6T4MWHON

heroku:
  dyno_adjuster_token: 3c7865fa-e80c-4e9f-a65a-12f23259c4a3

razorpay:
  MERCHANT_KEY_ID:  'rzp_live_RpAdyGJ65HXFGB'
  MERCHANT_KEY_SECRET:  'qfPQ2TRAPQxPAqQx8Msvrya9'

sap:
  ENDPOINT: 'https://35.200.144.191:50000/b1s/v1'
  DATABASE: 'BULKMRO_PRODUCTION'
  USERNAME: 'manager'
  PASSWORD: 'vm1234'
  ATTACHMENT_ENDPOINT: 'https://35.200.144.191:22'
  ATTACHMENT_DIRECTORY: '/usr/sap/SAPBusinessOne/B1_SHF/Attachments'
  ATTACHMENT_API: '35.200.144.191/b1_shf/Attachments'
  ATTACHMENT_USERNAME: 'pradeep'
  ATTACHMENT_PASSWORD: ''
  ATTACHMENT_SSH: '-----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEA9bBug/z3ZxZnfS4sBNolGjq3+JFWb8odFtq55m7w+zsAe6uC
  fPkIJaDdJfqwr6sk3991heT93CbqLf9ZWS6sDLJpQ2d5a/rEO8n2H10WPb1DmT9P
  YQC3zotMktGq7ENYL7QBDgXK1VOsV2JRnvSr6i8i9OQjOATp/1YxLdE0wh6/Qym5
  S+rU825YZED2GpeHJIVUvFuRjXFPASQQsV7BwM5Msp+FRWFmOlHilDDFpPjSQSOK
  lnkkaFBXPMox56OTb/+4Ihkmd+Oawl0ofuxWmlWUrzxevlL2Xa7EJki1WidrcXYI
  nqEW/afe/YMWZ/wDWO77QGfwUang+erBJBdfjwIDAQABAoIBAFzVRHz0yZqXGZVw
  K8vNjXViuH7gk7N7wBARp2qNgtq6yYzxGkYUZuKo7Mbb+YT2+uDoc2SbSNy1i4jD
  0kPjYbkOdL22TGfjgeBBiJEDQFMlv3QZOuohNlKByfYz6QyKybiEoF1nDOQcUKNY
  EBUqyAadtuyngzM4kB4duEliojeyXvYlUaTYOTJqlEhKoRPqYxgy/44+qw0Bt4ta
  ZeabeaNvRPMD9qnsBRz29Yfv0BIaXOYTZyWlg09pbmFuBEAHRwg6NQHgOuKHX9Hl
  v/x2gAdo8NrTPkLHiqc50hDjctHVPjiukxRea/J4OrwCgIkwER+Amozmx/df14BR
  KhdfkqkCgYEA+tRvT/kq2Fo0y0LrxPKT4obj1fcatQCFTn0+S4m68/iT1vAowX4w
  4XW6CEzZgxIl0/ngTjibl3+h4kFEUfp0OQkN+4EV0xzTTtBOybd1O6iaWB5zwu8c
  aSyJYlxSwbn8BVYl6z94NpG6lMoJo+QoGwH04tU+Ks61HbGe16xx040CgYEA+sDe
  /Uy8Ds63SQOx07njlbPIwu/SrQ+grxemHc2c1V8E+j+ghfU/pIwQcLqN6sDIUGjG
  fBw7oxWve4nKW2HqkDy7U1M/gW9IOL67fd0D1NfbDeGtcIDXvLqAj2c3lzYZ2CgF
  PTFTfJQJWvzN+b0/yAxcK+aIkoiCdPB6iDueCosCgYEApH1fqhB62nr9mDaAqx1x
  geJ30z9DUmPPCBP2IE9oPMpNGW1RLOL2Z0RvBTZwhhYGnKaHRIS29HkMznWCukgG
  o8ieVMroZxPGNy9AG+SlisQcw6DkxXdNKGO+jLSCyOyQq2c9YrKywQZ8V0rPW50p
  99wmngK9zBDWkWyEAGfkFZkCgYAtAroEVeXb8pdL7/HXw6JqmN8MvufeUNPTGjej
  WekxE+Fc2lcCNMe7zbiVw6b94KUUafpXBOpfl+DsGAvO44Cra3tktajMnyEjrnkR
  Wr75UdXsY/oyG66eHgw9sZV0+y0gc+6c0WHfFuOnBYIjtijgy/cvmi4hv4dLXm9g
  TPNNiQKBgQCvM1FiwATvx88AltNTeaCD3UzUr9ND2UnARYW+Fy4tJBYb0hUBtqeq
  tq7iFj/oZ0WuMVBpik7S47FVc9SeuWTUcbRwC87lF5aobMyUNIaxc06+4zR9Hl5X
  ulmwwTdSSRVmjSfz4OxPuSNQdXmYhHDkXMKfewl4mkEJSp92a1HHXw==
  -----END RSA PRIVATE KEY-----'